### PR TITLE
Use commissaire.util.config.import_plugin()

### PR DESCRIPTION
**Pull request by mbarnes**
Also, shorten the authentication plugin name in commissaire.conf and in test cases.

Requires: https://github.com/projectatomic/commissaire/pull/93

### CODE REVIEW

**Comment by ashcrow** [comment]
```
ERROR: Failure: ImportError (cannot import name 'import_plugin')
```

**Comment by mbarnes** [comment]
> `ERROR: Failure: ImportError (cannot import name 'import_plugin')`

That's expected until https://github.com/projectatomic/commissaire/pull/93 is merged.

**Comment by mbarnes** [comment]
@ashcrow Ping; this good to merge?

**Comment by ashcrow** [comment]
@mbarnes code is good. I believe the development docs need updating on how to create an ``Authentication`` plugin (http://commissaire.readthedocs.io/en/latest/authentication_devel.html).

**Comment by mbarnes** [comment]
@ashcrow Good catch.  Submitted https://github.com/projectatomic/commissaire/pull/94 for the docs update.

**Pull request merged**
