### PR TITLE
Add-to-cluster restrictions

### PR DESCRIPTION
**Pull request by mbarnes**
Fixes https://github.com/projectatomic/commissaire-http/issues/68

WIP until I verify the container manager E2E tests run successfully with this.

Note, this implementation feels brittle to me.  Consider it technical debt.

In the near future I'd like to have notification messages on the bus for storage changes, so services like container manager can be more autonomous: essentially do its own bookkeeping in response to change notifications from hosts and clusters.  This would keep `commissaire-http` handlers simpler and less error prone. 
**Ed:** see https://github.com/projectatomic/commissaire-service/issues/59

### CODE REVIEW

**Comment by ashcrow** [comment]
> Note, this implementation feels brittle to me. Consider it technical debt.

Does it feel brittle because you have a better future design or is it literally error prone?

**Comment by mbarnes** [comment]
> Does it feel brittle because you have a better future design or is it literally error prone?

I feel like some of the HTTP handlers are getting too complicated; and despite our exception handling, errors can still leave data and services in an inconsistent state.  Maybe "error prone" isn't quite right, but the number of places where errors *can* occur is both increasing and getting harder to recover from.

**Comment by mbarnes** [comment]
@ashcrow I think this is ready for review.

**Comment by ashcrow** [comment]
bot, please retest this

**Comment by ashcrow** [comment]
bot, retest this please

**Comment by ashcrow** [comment]
```
    host.status = C.HOST_STATUS_DISASSOCIATED
AttributeError: module 'commissaire.constants' has no attribute 'HOST_STATUS_DISASSOCIATED
```

Rerunning now that the constants are merged.

**Pull request merged**
