### PR TITLE
Call container manager methods

### PR DESCRIPTION
**Pull request by mbarnes**
Call `container.remove_node` when deleting a host.
Call `container.remove_all_nodes` when deleting a cluster.

### CODE REVIEW

**Comment by ashcrow** [comment]
Code looks good. What about ``delete_cluster_member``?

**Comment by mbarnes** [comment]
> Code looks good. What about `delete_cluster_member`?

Ah yes, good catch.  Fixup incoming.

**Comment by mbarnes** [comment]
@ashcrow :arrow_up:

**Comment by ashcrow** [comment]
Good work!

**Pull request merged**
