### PR TITLE
handlers: Map 'METHOD_NOT_ALLOWED' error to HTTP status 405.

### PR DESCRIPTION
**Pull request by mbarnes**
Related to https://github.com/projectatomic/commissaire-http/issues/68

Initial use case: attempting to add an `investigating`, `bootstrapping`, or `failed` host to a cluster.  More generally, for use when a request violates a semantic invariant.

Requires: https://github.com/projectatomic/commissaire/pull/110

### CODE REVIEW

**Comment by ashcrow** [comment]
bot, retest this please

**Comment by ashcrow** [comment]
@mbarnes looks like some tests are unhappy.

**Comment by mbarnes** [comment]
@ashcrow :arrow_up: I think the test failure is a side-effect of https://github.com/projectatomic/commissaire/commit/e0179985eaf0c775696806cad468f3cb84be70b3, but I can't explain why it was passing before; the test case was legitimately flawed.

**Comment by ashcrow** [comment]
@mbarnes odd. Good find though.

**Pull request merged**
