### PR TITLE
Return the subject token for authn use

### PR DESCRIPTION
**Pull request by gbraad**
Returning the subject token, as recevied from keystone, in the response to the client. This way a continued flow is possible without the user having to send credentials over the line for each consecutive request.

This would rely on:
  * #21 
  * #31 
  * #34 
  * and a client that takes the `X-Subject-Token` and uses this as the `X-Auth-Token`.

### CODE REVIEW

**Comment by ashcrow** [comment]
bot, test pull request

**Comment by gbraad** [comment]
I added try/except and changed the commit message

**Comment by ashcrow** [comment]
bot, test pull request

**Comment by ashcrow** [comment]
:+1:

**Pull request merged**
