### PR TITLE
Container manager endpoints

### PR DESCRIPTION
**Pull request by ashcrow**
Requires: https://github.com/projectatomic/commissaire/pull/50

Build failures expected until the above is merged.

Part of https://github.com/projectatomic/commissaire/issues/51

### CODE REVIEW

**Comment by ashcrow** [comment]
[(2) [multi-host-mgr-2] Store ContainerManager Configuration](https://trello.com/c/plCenTg2/554-2-multi-host-mgr-2-store-containermanager-configuration)

**Comment by mbarnes** [comment]
@ashcrow Removing the `CLUSTER_TYPE` constants in https://github.com/projectatomic/commissaire/pull/50 broke a test case:
```
======================================================================

ERROR: Verify get_host_status responds with status information.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/projectatomic/commissaire-http/test/test_handlers_hosts.py", line 317, in test_get_host_status

    host={'last_check': '', 'status': ''}, type=C.CLUSTER_TYPE_HOST)

AttributeError: module 'commissaire.constants' has no attribute 'CLUSTER_TYPE_HOST'
```

**Comment by ashcrow** [comment]
Fixing

**Comment by ashcrow** [comment]
:arrow_up:

**Pull request merged**
